# Generated by Django 5.2.13 on 2026-05-15 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=100)),
                ('med_ch', models.CharField(max_length=100)),
                ('med_en', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('shape', models.CharField(blank=True, max_length=50, null=True)),
                ('indications', models.TextField(blank=True, null=True)),
                ('element', models.TextField(blank=True, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugWarning',
            fields=[
                ('warning_id', models.AutoField(primary_key=True, serialize=False)),
                ('conflict_target', models.CharField(max_length=255)),
                ('warning_desc', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.drug')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=50)),
                ('visit_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='prescriptions/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=255)),
                ('total_amount', models.IntegerField()),
                ('frequency', models.CharField(max_length=20)),
                ('days', models.IntegerField()),
                ('remaining_amount', models.IntegerField(blank=True, null=True)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Remind',
            fields=[
                ('remind_id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency_tag', models.CharField(max_length=50)),
                ('remind_time', models.TimeField()),
                ('prescription_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.prescriptiondrug')),
            ],
        ),
        migrations.CreateModel(
            name='TakingRecord',
            fields=[
                ('takingrecord_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('taken_at', models.DateTimeField()),
                ('remind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.remind')),
            ],
        ),
    ]
