# Generated by Django 6.0.4 on 2026-04-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=100)),
                ('med_ch', models.CharField(max_length=100)),
                ('med_en', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('shape', models.CharField(blank=True, max_length=50, null=True)),
                ('indications', models.TextField(blank=True, null=True)),
                ('element', models.TextField(blank=True, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
