# Generated by Django 5.2.17 on 2026-09-18 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_medicationreminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_code', models.CharField(max_length=50)),
                ('drug_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('days', models.IntegerField()),
                ('hosp_name', models.CharField(max_length=100)),
                ('rx_date', models.DateField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '健康存摺藥歷',
                'verbose_name_plural': '健康存摺藥歷',
            },
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('allergy_id', models.AutoField(primary_key=True, serialize=False)),
                ('allergen_name', models.CharField(max_length=255)),
                ('reaction', models.TextField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '患者過敏原',
                'verbose_name_plural': '患者過敏原',
            },
        ),
        migrations.DeleteModel(
            name='MedicationReminder',
        ),
    ]
