# Generated by Django 6.0.4 on 2026-05-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='image_url',
        ),
        migrations.AddField(
            model_name='prescription',
            name='image',
            field=models.ImageField(default=None, upload_to='prescriptions/'),
            preserve_default=False,
        ),
    ]
