# Generated by Django 5.2.13 on 2026-09-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_medicationreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='remind',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
