# Generated by Django 6.0.4 on 2026-05-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_remove_prescription_image_url_prescription_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
