# Generated by Django 5.2.13 on 2026-09-18 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_remind_is_active_delete_medicationreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='takingrecord',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='takingrecord',
            name='taken_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='takingrecord',
            constraint=models.UniqueConstraint(fields=('remind', 'record_date'), name='unique_remind_record_date'),
        ),
    ]
