# Generated by Django 6.0.4 on 2026-05-08 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_alter_prescription_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('warning_id', models.AutoField(primary_key=True, serialize=False)),
                ('conflict_target', models.CharField(max_length=255)),
                ('warning_desc', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.drug')),
            ],
        ),
    ]
