# Generated by Django 5.2.13 on 2026-09-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_takingrecord_record_date_alter_takingrecord_taken_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='remind',
            constraint=models.UniqueConstraint(fields=('prescription_drug', 'frequency_tag'), name='unique_prescription_drug_frequency_tag'),
        ),
    ]
