# Generated by Django 5.2.17 on 2026-09-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_medicationhistory_patientallergy_and_more'),
        ('medications', '0005_remind_unique_prescription_drug_frequency_tag'),
    ]

    operations = [
    ]
