# Generated by Django 6.0.4 on 2026-05-08 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_warning'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warning',
            new_name='DrugWarning',
        ),
    ]
