# Generated by Django 5.2.17 on 2026-10-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_merge_20260920_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationhistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patientallergy',
            options={},
        ),
        migrations.AlterField(
            model_name='drug',
            name='license',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
