# Generated by Django 6.0.6 on 2026-10-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0007_alter_medicationhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remind',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
