# Generated by Django 6.0.4 on 2026-05-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0007_prescriptiondrug'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiondrug',
            name='remaining_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
