# Generated by Django 5.2.13 on 2026-05-10 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0008_alter_prescription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptiondrug',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.drug'),
        ),
    ]
