# Generated by Django 6.0.4 on 2026-05-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0008_prescriptiondrug_remaining_amount'),
        ('medications', '0009_alter_prescriptiondrug_drug'),
    ]

    operations = [
    ]
