# Generated by Django 6.0.4 on 2026-05-12 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0010_merge_20260512_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remind',
            fields=[
                ('remind_id', models.AutoField(primary_key=True, serialize=False)),
                ('frequency_tag', models.CharField(max_length=50)),
                ('remind_time', models.TimeField()),
                ('prescription_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.prescriptiondrug')),
            ],
        ),
        migrations.CreateModel(
            name='TakingRecord',
            fields=[
                ('takingrecord_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('taken_at', models.DateTimeField()),
                ('remind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.remind')),
            ],
        ),
    ]
