# Generated by Django 5.2.17 on 2026-10-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_groupmember_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='unique_group_member'),
        ),
    ]
