# Generated by Django 5.2.17 on 2026-10-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_groupmember_unique_group_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='id',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group_member_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
